name: Build and Deploy Next.js with Docker

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: 检出代码
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: 设置 Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: 登录 Docker Registry（如果需要推送镜像到远程仓库）
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 4: 构建 Docker 镜像
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true # 如果需要推送到 DockerHub，请保留 true
          tags: your-dockerhub-username/your-repo-name:latest

      # Step 5: 部署到服务器（SSH）
      - name: Deploy to Server
        uses: appleboy/ssh-action@v0.5.4
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            docker pull whispora/web-tarnsformer:latest
            docker stop whispora/web-tarnsformer || true
            docker rm whispora/web-tarnsformer || true
            docker run -d --name whispora/web-tarnsformer -p 7788:7788 whispora/web-tarnsformer:latest
